src/components/BoardList.component.jsx, src/components/Navbar.component.jsx, src/css/BoardList.component.css, src/css/Navbar.component.css
hello. i added search and state management to the board component, and made slight changes to the navbar,
=> Board Searching & tiny Navbar UI enhancment 

src/components/TableList.component.jsx, src/css/CreateRow.component.css, src/css/TableList.component.css
Centered table that was to the left using margin auto
=> Centered table

src/components/CreateArea.component.jsx
Adjusted the title box to fit in the note and made the background of the input box transparent.
This fixes issue #15 
Let me know if you want me to make any changes to this pull request.
=> Adjusted title box to fit in the note

package-lock.json, package.json, src/components/Board.jsx, src/components/CreateArea.jsx, src/components/CreateBoard.jsx, src/components/CreateRow.jsx, src/components/Note.jsx, src/components/Row.jsx, src/index.js, src/pages/NoteList.jsx, src/pages/TableList.jsx, src/styles/NoteList.css
i have add few thing in the sticky note web app like
-> add a functionality for making change to the existing sticky notes.
-> i have notification for any warning or any message.
-> I have use react toastify for that 
however, there are one issue which i have not resolve. and that is, CSS designing i have not design the text area of making change in existing sticky notes.. 
however you can do that. if you want.
=> Editing existing sticky Notes

Contributors.md, src/components/Note.jsx, src/components/Row.jsx, src/pages/TableList.jsx, src/styles/BoardList.css, src/styles/Button.css, src/styles/NoteList.css, src/styles/TableList.css
- added button based button activation for reducing cluttering
- updated Row & Notes Component
- Standardised color for buttons
=> fix: updated UI/UX across Notes & Rows components

src/components/Board.jsx, src/pages/BoardList.jsx, src/pages/NoteList.jsx, src/pages/TableList.jsx, src/styles/BoardList.css, src/styles/Button.css, src/styles/NoteList.css, src/styles/utils.css
- updated board UI
- button changes
- CreateBoard changes
=> fix: updated board component UI/UX

src/pages/BoardList.jsx, src/pages/TableList.jsx, src/styles/BoardList.css, src/styles/Button.css, src/styles/NoteList.css, src/styles/TableList.css
- updated common animation
- ease-in background-color animations across notes, boards, tables
- comments for better understanding
=> fix: updated common styles & animation across application

src/pages/Navbar.jsx, src/styles/Navbar.css
- updated navbar
- color changes
=> fix: updated navbar

src/pages/BoardList.jsx, src/pages/NoteList.jsx, src/pages/TableList.jsx
- added comments for Pages react component
=> fix: coding comments for components

src/pages/Footer.jsx, src/pages/Navbar.jsx
- refactored & added comments the following components:
- Navbar.jsx
- Footer.jsx
=> feat(refactor): add navigation items and profile dropdown

src/components/Board.jsx, src/components/CreateBoard.jsx, src/components/CreateNote.jsx, src/components/Note.jsx, src/styles/Button.css, src/styles/NoteList.css, src/styles/TableList.css
- added animation effects for button clickable actions
- refactorted the code for `buttons.css` , `Note.jsx`, `Board.jsx`
=> feat(buttons): updated buttons animation effects & refactored the code

src/pages/BoardList.jsx, src/pages/TableList.jsx, src/styles/BoardList.css, src/styles/NoteList.css, src/styles/TableList.css
- Updated notes overflow 
- Common scrollbar UI & notes
- Boards content same as input
=> fix(UI): updated small UI issues

.github/workflows/greetings.yml
- Updated the job to trigger only on main
- Only triggers once after it merges to main from other branches
=> Fix(runners): updated the first interactions workflow

src/App.jsx, src/pages/BoardList.jsx, src/pages/NoteList.jsx, src/pages/TableList.jsx, src/styles/BoardList.css
Overflow wasn't due to buttons css .  Content overflow has been resolved .
=> made neccessary changes

src/App.jsx, src/pages/BoardList.jsx, src/pages/NoteList.jsx, src/pages/TableList.jsx, src/styles/BoardList.css
=> Fix(notes): Overflow of notes fixed

package-lock.json, package.json, src/components/Navbar.jsx
=> chore(route): updated the routes

package-lock.json, package.json, src/components/CreateBoard.jsx, src/components/CreateNote.jsx, src/components/CreateRow.jsx, src/components/Navbar.jsx, src/main.jsx, src/pages/BoardList.jsx, src/pages/NoteList.jsx, src/pages/TableList.jsx, src/utils/useItemUtils.js
- Changed the routes in Navbar & removed the profile dropdown
- Fixed few bugs
=> feat(UI): Updated the MUI styling & toast

src/App.jsx, src/components/Loading/index.jsx, src/main.jsx, src/pages/NotFoundPage/index.jsx
Hii, 
I add two new thing to Website.
1. Loading Spinner
2. NotFound Page
=> New Features 

src/App.jsx, src/components/CreateBoard.jsx, src/components/CreateNote.jsx, src/components/CreateRow.jsx, src/components/Loading/index.jsx, src/main.jsx, src/pages/BoardList.jsx, src/pages/NotFoundPage/index.jsx, src/pages/NoteList.jsx, src/pages/TableList.jsx, src/utils/helper.js, src/utils/state.js, src/utils/useItemUtils.js
- Updated the snackbar MUI for all notes, boards & rows
- Held, checked, deleted, created snackbar notifications
=> fix(notification): notification alert changed

src/App.jsx, src/components/Table/TableCard.jsx, src/components/common/Navbar.jsx, src/components/common/styles.js, src/pages/BoardList.jsx, src/pages/NoteList.jsx, src/pages/TableList.jsx
- released first version of sticky memo
- needs automated `.yaml` file for versioning and releasing notes
- Has integrated features of MUI theme, refactored code into separate directories 
- Will work on more patches and bugs in future
=> feat(tags): created the v1.0.0 version

.github/workflows/greetings.yml, src/components/common/CommonSort.jsx, src/pages/BoardList.jsx, src/pages/NoteList.jsx, src/pages/TableList.jsx
- Updated the Sort feature for all Lists - `Notes`, `Boards`, `Table`
- Needs the UI improvement, will continue to work on it.
=> fea(sort): Addition of Sort Feature

package-lock.json, package.json, src/App.jsx, src/components/common/Navbar.jsx, src/pages/RoadmapView.jsx
What's New:
- Added a dedicated Roadmap view component.
- Integrated routing for the Roadmap page.
- Updated navigation to include the new view.
=> Feat(Roadmap): Added Roadmap view to the existing views

.github/workflows/ISSUE_TEMPLATE/feature_request.md
This PR adds a GitHub Issue Template for feature requests in the repository.
- `.github/ISSUE_TEMPLATE/feature_request.md`
- Includes metadata (`name`, `about`, `labels`, `assignees`)
- Markdown checklist to guide contributors when requesting new features
- The template appears when creating a new issue
- Labels are auto-assigned as expected
- Task checklist and description sections help guide contributors
Let me know if you’d like any changes or additions!
=> Add feature request issue template

package-lock.json, package.json, src/App.jsx, src/components/Board/BoardCard.jsx, src/components/Note/NoteCard.jsx, src/components/Table/TableCard.jsx, src/pages/BoardList.jsx, src/pages/NoteList.jsx, src/pages/TableList.jsx, src/utils/helper.js
📋 Tasks Completed [#96]
1. Assign UUIDs on Item Creation
2. Refactor All CRUD Logic
Update logic in /src/utils/helper.js and relevant services/contexts.
3. Update React List Keys
4. Audit and Refactor UI Components
5. Test All User Interactions
6. Update Documentation
=> [Fix]: Array Index IDs Cause Deletion/Update Bugs – Migrate to UUIDs' [#96]

src/components/Note/NoteSorter.jsx, src/pages/NoteList.jsx, src/utils/helper.js
This PR introduces sorting functionality for notes based on multiple criteria: **Checked status**, **Hold status**, and **Alphabetical order by title**. It ensures smooth user experience and seamless integration with the existing filter functionality.
---
- Added `NoteSorter` component with a dropdown for:
- ✅ Checked
- ❎ Unchecked
- 🛑 Hold
- 🟢 Unhold
- ⬇️ Title A → Z
- ⬆️ Title Z → A
📄 **File:** `src/components/Note/NoteSorter.jsx`
---
- Introduced `sort` state to manage selected sorting criteria.
- Applied sorting *after* filtering to ensure the correct order of operations.
- Managed sorting inside `useEffect` to update `displayItems` reactively.
📄 **File:** `src/pages/NoteList.jsx`
---
- Added helper functions to handle:
- `sortItemsByChecked()`
- `sortItemsByHold()`
- …
=> Gd Sorting Functionality Issue #54

index.html, src/pages/LandingPage.jsx
Updated the Hero section of the Sticky Memo landing page with essential layout and styling. This includes a full-width layout, gradient background, text color adjustment, and visual depth through box shadow. These changes set the foundation for further enhancements like animation, CTA buttons, and responsive typography.
Add any other context about the pull request here.
=> Static Landing Page for Sticky-Memo , UI updates
